name: Test, Build, and Deploy with GameCI
on: [push, pull_request]
 # push:
 #   branches:
 #     — develop
 #     - main
 #   # paths:
 #   #   — ‘Assets/**’
 #   #   — ‘Packages/**’
 #   #   — ‘ProjectSettings/**’
 # pull_request:
 #   types:
 #     — opened
 #   branches:
 #     — main
 #   paths:
 #     — ‘Assets/**’
 #     — ‘Packages/**’
 #     — ‘ProjectSettings/**’
 # # release:
 # #   types:
 # #     — published
 # # workflow_dispatch:
 # #   inputs:
 # #     workflow_mode:
 # #       description: ‘[release] [Android, iOS, StandaloneLinux64, WebGL, StandaloneWindows, StandaloneWindows64, WSAPlayer, StandaloneOSX, Steam]’
 # #       required: false
 # #       default: ‘’
jobs:
  build:
    uses: ./.github/workflows/build.yml
  deployToGitHubPages:
    needs: build
    uses: ./.github/workflows/build_web.yml
    
