name: Test, Build, and Deploy with GameCI
on:
 push:
   branches:
     — develop
   # paths:
   #   — ‘Assets/**’
   #   — ‘Packages/**’
   #   — ‘ProjectSettings/**’
 pull_request:
   types:
     — opened
   branches:
     — main
   paths:
     — ‘Assets/**’
     — ‘Packages/**’
     — ‘ProjectSettings/**’
 release:
   types:
     — published
 workflow_dispatch:
   inputs:
     workflow_mode:
       description: ‘[release] [Android, iOS, StandaloneLinux64, WebGL, StandaloneWindows, StandaloneWindows64, WSAPlayer, StandaloneOSX, Steam]’
       required: false
       default: ‘’
jobs:
  buildWithLinux:
    uses: ./.github/workflows/build_linux.yml
  deployToGitHubPages:
    needs: buildWithLinux
    uses: ./.github/workflows/build_web.yml
    
